import pytest

from data import Piece
from janggi import Janggi
from formation import parse
from rule import next_coordinates, next_possible_coordinates


@pytest.fixture(scope='function')
def empty_board():
    return Janggi().board


def test_cha_mobility(empty_board):
    coords = set(next_possible_coordinates(empty_board, 1, 1, Piece.Cha_a))

    up = {(0, 1)}
    down = {(2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1)}
    left = {(1, 0)}
    right = {(1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8)}
    assert coords == left | right | up | down


def test_byung_mobility(empty_board):
    coords = set(next_possible_coordinates(empty_board, 2, 2, Piece.Jol_a))

    down, left, right = (3, 2), (2, 1), (2, 3)
    assert coords == {down, left, right}


def check_mobility(spec):
    """
    @param spec - 다음의 문자(열)로 구성된 문자열
        o       - 움직일 기물
        대문자  - 갈 수 있는곳
        소문자  - 갈 수 없는곳
        .       - 빈칸 (갈 수 없는곳)
        공백    - 무시됨
        줄바꿈  - 행구분
        c=Cha_a - 사용된 문자와 기물 매핑
    """
    pos, pieces, expected_coords = parse(spec)
    assert pos, 'o should be specified once'
    janggi = Janggi()
    for i, j, p in pieces:
        janggi.board[i][j] = p
    piece = janggi.board[pos[0]][pos[1]]
    coords = set(next_coordinates(janggi.board, *pos, piece))
    assert coords == expected_coords


def test_cha_cannot_pass_enemy():
    check_mobility('''
        .........
        ....q....  q=Kung_a
        .........
        .........
        ........A  A=Cha_a
        XXXXXXXXo  o=Cha_b
        ........X
        ........X
        ....k...X  k=Kung_b
        ........X
    ''')


def test_jol_mobility():
    check_mobility('''
        .........
        .........
        .........
        .........
        .........
        .........
        ....X....
        ...joX...  j=o=Jol_b
        ....k....  k=Kung_b
        .........
    ''')


def test_kung_cannot_cross_line():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        .........
        .........
        .........
        ...XoX...  o=Kung_b
        ...-X-...
        .../|\...
    ''')


def test_cha_at_palace_center():
    check_mobility(r'''
        ...\X/...
        ...-X-...
        .../X\...
        ....X....
        ....X....
        ....X....
        ....X....
        ...XXX...
        XXXXoXXXX  o=Cha_b
        ...XXX...
    ''')

    check_mobility(r'''
        ...XXX...
        XXXXoXXXX  o=Cha_a
        ...XXX...
        ....X....
        ....X....
        ....X....
        ....X....
        ...\X/...
        ...-X-...
        .../X\...
    ''')

    check_mobility(r'''
        ...Xkk...  k=Sa_a
        XXXXoXXXX  o=Cha_a
        ...XXX...
        ....X....
        ....X....
        ....X....
        ....X....
        ...\X/...
        ...-X-...
        .../X\...
    ''')


def test_cha_in_palace():
    check_mobility(r'''
        ...\|X...
        ...-+X...
        .../|X...
        .....X...
        .....X...
        .....X...
        .....X...
        ...X|X...
        ...-XX...
        XXXXXoXXX  o=Cha_b
    ''')

    check_mobility(r'''
        ...\|X...
        ...-+X...
        .../|X...
        .....X...
        .....X...
        .....X...
        .....X...
        ....|X...
        ...-kX...  k=Kung_b
        XXXXXoXXX  o=Cha_b
    ''')

    check_mobility(r'''
        ...\X/...
        ...-X-...
        .../X\...
        ....X....
        ....X....
        ....X....
        ....X....
        ...XXX...  s=Sa_b
        ...sok...  k=Kung_b
        ...XsX...  o=Cha_b
    ''')


def test_po_in_palace():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        .........
        .........
        .........
        ...X|/...
        ...-k-...  k=Kung_a
        .../|o...  o=Po_b
    ''')

    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        .........
        .........
        .........
        ...\|/...
        ...-p-...  k=Po_a
        .../|o...  o=Po_b
    ''')

    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        .........
        .........
        .........
        ...p|/...  p=Po_a
        ...-c-...  c=Cha_b
        .../|o...  o=Po_b
    ''')


def test_po_cannot_take_po():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        ....o....  o=Po_b
        .........
        ....c....  c=Cha_b
        ...\X/...
        ...-p-...  p=Po_a
        .../|\...
    ''')


def test_po_cannot_jump_po():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        ....o....  o=Po_b
        .........
        ....p....  p=Po_b
        ...\|/...
        ...-+-...
        .../|\...
    ''')

    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        ....o....  o=Po_b
        .........
        ....p....  p=Po_a
        ...\|/...
        ...-+-...
        .../|\...
    ''')


def test_po_cannot_take_same_team():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        ....o....  o=Po_b
        ....c....  c=Cha_b
        ....X....
        ...\X/...
        ...-k-...  k=Kung_b
        .../|\...
    ''')


def test_po_separate_check_for_each_diagonal_direction():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        .........
        .........
        .........
        ...c|/...  c=Cha_b
        ...-o-...  o=Po_b
        .../|\...
    ''')


def test_ma():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        .........
        ..X.x.X..
        ....o....  s=Sang_b
        ..X...s..  x=Jol_a
        ...X|X...  o=Ma_b
        ...-+-...
        .../|\...
    ''')


def test_sang():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\X..
        .X.x...s.
        .........
        ....o....  s=Sang_b
        ....x....  x=Jol_a
        .X.\|/.X.  o=Sang_b
        ...-+-...
        .../|\...
    ''')


def test_jol_in_palace():
    check_mobility(r'''
        ...XXX...
        ...XoX...  o=Jol_b
        .../|\...
        .........
        .........
        .........
        .........
        ...\|/...
        ...-+-...
        .../|\...
    ''')


def __test_byung_move():
    check_mobility(r'''
        ...\|/...
        ...-+-...
        .../|\...
        ...XoX...  o=Jol_a
        ....X....
        .........
        .........
        ...\|/...
        ...-+-...
        .../|\...
    ''')
